- name: Pull nginx image
  hosts: all
  become: yes
  collections:
    - community.docker
  tasks:
    - name: Pull nginx latest image
      docker_image:
        name: nginx
        tag: latest
        source: pull
